# Generated by Django 3.2.9 on 2021-12-28 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='updated_on',
            new_name='updated_at',
        ),
    ]
