# Generated by Django 3.2.9 on 2022-01-09 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220109_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hood_post', to='app.neighborhood'),
        ),
    ]
