# Generated by Django 3.2.9 on 2022-01-04 07:34

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_neighborhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='hood_description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='hood_image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='hood_image'),
        ),
    ]
