# Generated by Django 3.2.9 on 2022-01-09 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_post_hood'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='hood',
            new_name='hoods',
        ),
    ]
