# Generated by Django 3.2.9 on 2022-01-09 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_hood_post_hoods'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='hoods',
            new_name='hood',
        ),
    ]
